PATH: /media/diego/QData/youtube_out/frames/PLNP_nRm4k4jdEQ-OM31xNqeE64svvx-aT_CNN-Wendy/
NUM_CLASSES: 7
MODEL_NAME: mblade_categorizer.hdf5
STATES: ['BATTLE', 'HIDEOUT', 'SIEGE', 'TOURNAMENT', 'TOWN', 'TRAINING', 'UNKNOWN']
DEFAULT_STATE: 6
